export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const ADMIN_REGISTER_REQUEST = 'ADMIN_REGISTER_REQUEST';
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS';
export const ADMIN_REGISTER_FAIL = 'ADMIN_REGISTER_FAIL';

export const ADMIN_LIST_REQUEST = 'ADMIN_LIST_REQUEST';
export const ADMIN_LIST_SUCCESS = 'ADMIN_LIST_SUCCESS';
export const ADMIN_LIST_FAIL = 'ADMIN_LIST_FAIL';
export const ADMIN_LIST_RESET = 'ADMIN_LIST_RESET';

export const ADMIN_GET_STATS_REQUEST = 'ADMIN_GET_STATS_REQUEST';
export const ADMIN_GET_STATS_SUCCESS = 'ADMIN_GET_STATS_SUCCESS';
export const ADMIN_GET_STATS_FAIL = 'ADMIN_GET_STATS_FAIL';

export const ADMIN_USER_LIST_REQUEST = 'ADMIN_USER_LIST_REQUEST';
export const ADMIN_USER_LIST_SUCCESS = 'ADMIN_USER_LIST_SUCCESS';
export const ADMIN_USER_LIST_FAIL = 'ADMIN_USER_LIST_FAIL';

export const ADMIN_USER_DETAILS_REQUEST = 'ADMIN_USER_DETAILS_REQUEST';
export const ADMIN_USER_DETAILS_SUCCESS = 'ADMIN_USER_DETAILS_SUCCESS';
export const ADMIN_USER_DETAILS_FAIL = 'ADMIN_USER_DETAILS_FAIL';

export const ADMIN_USER_UPDATE_REQUEST = 'ADMIN_USER_UPDATE_REQUEST';
export const ADMIN_USER_UPDATE_SUCCESS = 'ADMIN_USER_UPDATE_SUCCESS';
export const ADMIN_USER_UPDATE_FAIL = 'ADMIN_USER_UPDATE_FAIL';
export const ADMIN_USER_UPDATE_RESET = 'ADMIN_USER_UPDATE_RESET';

export const ADMIN_USER_DELETE_REQUEST = 'ADMIN_USER_DELETE_REQUEST';
export const ADMIN_USER_DELETE_SUCCESS = 'ADMIN_USER_DELETE_SUCCESS';
export const ADMIN_USER_DELETE_FAIL = 'ADMIN_USER_DELETE_FAIL';

export const ADMIN_USER_CREATE_REQUEST = 'ADMIN_USER_CREATE_REQUEST';
export const ADMIN_USER_CREATE_SUCCESS = 'ADMIN_USER_CREATE_SUCCESS';
export const ADMIN_USER_CREATE_FAIL = 'ADMIN_USER_CREATE_FAIL';
export const ADMIN_USER_CREATE_RESET = 'ADMIN_USER_CREATE_RESET';
