// Review list constants
export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST';
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS';
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL';
export const REVIEW_LIST_RESET = 'REVIEW_LIST_RESET';

// Review details constants
export const REVIEW_DETAILS_REQUEST = 'REVIEW_DETAILS_REQUEST';
export const REVIEW_DETAILS_SUCCESS = 'REVIEW_DETAILS_SUCCESS';
export const REVIEW_DETAILS_FAIL = 'REVIEW_DETAILS_FAIL';
export const REVIEW_DETAILS_RESET = 'REVIEW_DETAILS_RESET';

// Review update status constants
export const REVIEW_UPDATE_STATUS_REQUEST = 'REVIEW_UPDATE_STATUS_REQUEST';
export const REVIEW_UPDATE_STATUS_SUCCESS = 'REVIEW_UPDATE_STATUS_SUCCESS';
export const REVIEW_UPDATE_STATUS_FAIL = 'REVIEW_UPDATE_STATUS_FAIL';
export const REVIEW_UPDATE_STATUS_RESET = 'REVIEW_UPDATE_STATUS_RESET';

// Review delete constants
export const REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST';
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS';
export const REVIEW_DELETE_FAIL = 'REVIEW_DELETE_FAIL';
export const REVIEW_DELETE_RESET = 'REVIEW_DELETE_RESET';

// Review statistics constants
export const REVIEW_STATS_REQUEST = 'REVIEW_STATS_REQUEST';
export const REVIEW_STATS_SUCCESS = 'REVIEW_STATS_SUCCESS';
export const REVIEW_STATS_FAIL = 'REVIEW_STATS_FAIL';

// Review host response constants
export const REVIEW_HOST_RESPONSE_REQUEST = 'REVIEW_HOST_RESPONSE_REQUEST';
export const REVIEW_HOST_RESPONSE_SUCCESS = 'REVIEW_HOST_RESPONSE_SUCCESS';
export const REVIEW_HOST_RESPONSE_FAIL = 'REVIEW_HOST_RESPONSE_FAIL';
export const REVIEW_HOST_RESPONSE_RESET = 'REVIEW_HOST_RESPONSE_RESET';
